version: "3"

services:
  chatbot-api-server:
    image: chatbot-gpu-runtime:latest
    container_name: chatbot-api-server
    build: .
    volumes:
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    restart: always
    environment:
      CONFIG_FILE: /app/config.json
    entrypoint: ["python3"]
    command: ["main.py"]
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
