version: "3"

services:
  chatglm:
    image: chatglm-runtime:latest
    container_name: chatglm
    build: .
    volumes:
      - ./:/app
      - /path/to/model:/model/chatglm-6b:ro
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    environment:
      PRETRAINED: /model/chatglm-6b
    entrypoint: ["python3"]
    command: ["main.py"]
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]